Zimbra/zm-build

README.md

Added basic instructions for setting up a machine for
doing ZCS development.

ZCS-816 Developer set-up instructions

---

rpmconf/Upgrade/zmupgrade.pm

ZCS-1096: Adding missing 8.7.7 upgrade step

ZCS-1096: Adding missing 8.7.7 upgrade step

---

instructions/FOSS_repo_list.pl

This is required to pick-up the template changes.  **Note:** I have created Ubuntu 16 builds of `nginx` that will work with this and will send out email to the team.

ZMS-625 Build feature/imap branch of zm-nginx-conf

---

rpmconf/Install/Util/globals.sh

ZCS-1093: Add option to install ZSP
ZCS-1094: Create RPM and DEB packages for ZSP

ZCS-1093, ZCS-1094: Add option to install ZSP and corresponding packages

---

instructions/bundling-scripts/zimbra-core.sh
instructions/bundling-scripts/zimbra-store.sh

ZCS-984 Upgrading xercesImpl to 2.9.1-patch-01

ZCS-984 Upgrading xercesImpl to 2.9.1-patch-01

---

rpmconf/Install/Util/modules/packages.sh

Removed the code to download memcached after addition of epoch via zcs-414.

Removed the code to download memcached after addition of epoch via zcs-414

---

rpmconf/Install/zmsetup.pl

Disable backup scheduling on fresh install.

ZCS-1807: Disable backup scheduling on fresh install.

---

instructions/FOSS_staging_list.pl

Update the build script to result in completed build, but marked a failed, if tests fail.

ZCS-2183: Update the build script to result in completed build, but marked a failed, if tests fail

---

rpmconf/Install/Util/globals.sh
rpmconf/Install/Util/utilfunc.sh
rpmconf/Install/zmsetup.pl

* Also added code to disable zimlets after installation/upgrade.

ZCS-3013: bundled rpost rpm and debian package in install script.

---

rpmconf/Upgrade/zmupgrade.pm

Increments the DB version. Accompanies Zimbra/zm-mailbox#488, Zimbra/zm-db-conf#2

HA mailbox, redolog

---

instructions/bundling-scripts/zimbra-core.sh

Pick and add zmsearchNdelete script in /opt/zimbra/libexec/
Linked PR - https://github.com/Zimbra/zm-core-utils/pull/10
https://github.com/Zimbra/zm-core-utils/pull/11

NICPS-19 : Search and Delete

---

rpmconf/Install/Util/globals.sh
rpmconf/Install/Util/utilfunc.sh

* When removing an install, was failing on Ubuntu because wasn't trying to remove a complete list.
* When doing a install was prompting whether wanted to install the new license base packages.
They should always be installed on a mailstore node.  Tried to make the script cleaner here.

ZCS-4347 installer issues

---

rpmconf/Install/zmsetup.pl

On upgrade, was seeing:
Modifying GLOBALCONFIG globalconfig
zimbraMtaPostscreenDnsblWhitelistThreshold: 0
Caught ServiceException while modifying global config attribute zimbraMtaPostscreenDnsblWhitelistThreshold
com.zimbra.cs.ldap.LdapException$LdapObjectClassViolationException: object class violation - unable to modify attributes: ldap host=zqa-371.eng.zimbra.com:389: object class 'zimbraGlobalConfig' requires attribute 'zimbraLDAPSchemaVersion'
ExceptionId:main:1521434195320:edd59a1fd07c5007
Code:ldap.OBJECT_CLASS_VIOLATION
at com.zimbra.cs.ldap.LdapException.OBJECT_CLASS_VIOLATION(LdapException.java:134)
at com.zimbra.cs.ldap.unboundid.UBIDLdapException.mapToLdapException(UBIDLdapException.java:60)
at com.zimbra.cs.ldap.unboundid.UBIDLdapContext.mapToLdapException(UBIDLdapContext.java: …

ZCS-4592:Set zimbraLDAPSchemaVersion early

---

rpmconf/Install/Util/utilfunc.sh

ZCS-4637:install prompts wrong

---

instructions/FOSS_repo_list.pl
instructions/FOSS_staging_list.pl
instructions/bundling-scripts/zimbra-store.sh

Creating build for zm-oauth-social
Included the repo in FOSS repo list
Added publish-local to the staging list.
Created extension dir and added 2 jars to the target dir

ZCS-3349 Creating build for oauth-social

---

instructions/FOSS_repo_list.pl
instructions/FOSS_staging_list.pl
instructions/bundling-scripts/zimbra-store.sh

ZCS-5738 Building zm-gql extension

---

rpmconf/Install/Util/utilfunc.sh

NICPS-589: Update public repo tag to 8812

NICPS-589: Update public repo tag to 8812

---

instructions/bundling-scripts/zimbra-store.sh

Copy owasp config file at /opt/zimbra/conf location
Reference PR: https://github.com/Zimbra/zm-mailbox/pull/885

ZCS-7105:OWASP Policy configuration

---

rpmconf/Install/zmsetup.pl

NICPS-589: Update truststore path

NICPS-589: Update truststore path

---

rpmconf/Upgrade/zmupgrade.pm

Setting owasp flag to true during upgrade

ZCS-7589 Setting owasp flag to true during upgrade

---

instructions/FOSS_remote_list.pl
instructions/FOSS_repo_list.pl
instructions/FOSS_staging_list.pl

Upgrading owasp Antisamy library to latest version, with added fix for ZBUG-1174 in new antisamy library
Ref PRs:
https://github.com/Zimbra/zm-build/pull/157
https://github.com/Zimbra/zm-mailbox/pull/982
https://github.com/Zimbra/zm-zcs-lib/pull/57
https://github.com/Zimbra/antisamy/pull/1

ZBUG-1174: Web client does not show UTF-8 "Quoted-Printable"

---

instructions/bundling-scripts/zimbra-store.sh

Include the Tika app extractor which include all run time parser dependencies.

ZBUG-148 Fixing Tika extractor

---

instructions/FOSS_staging_list.pl
instructions/bundling-scripts/zimbra-store.sh

Adding the oauth social jars to the appropriate dir

ZCS-9728 Adding oauth social jar to build script

---

rpmconf/Install/Util/globals.sh
rpmconf/Install/zmsetup.pl

**Problem:**
When during upgrade from zcs 9.0 to 9.1 beta, found some issues related to zextras.
- There was a description about "zextras" in Privacy Policy
- com_zextras_zextras and com_zextras_client zimlet which had been installed on 9.0 were not removed at 9.1 upgrade install.

ZCS-10939 : Changes for 9.1.0

---

rpmconf/Upgrade/zmupgrade.pm

**Problem Statement**
Add new a column store_manager_class in zimbra.volume
**Solution**
Added mechanism to add new column for fresh install and upgrade scenario as well
Related PR's
- https://github.com/Zimbra/zm-mailbox/pull/1331
- https://github.com/Zimbra/zm-build/pull/214/files
- https://github.com/Zimbra/zm-db-conf/pull/27

ZCS-11725 StoreManager: Add new a column store_manager in zimbra.volume table

---

instructions/bundling-scripts/zimbra-store.sh

copy zm-store-manager into zimbrahsm dir

Feature/zcs 11775 copy zm-store-manager into zimbrahsm dir

---

rpmconf/Install/zmsetup.pl

**Problem** : Java options are not set during upgrade from 8812 latest patch to 8815 latest patch.
**Fix:** zimbra-patch adding java options but these options are getting override while during upgrade because in upgrade installer will restore localconfig options from existing configuration file /opt/zimbra/.saveconfig/localconfig.xml. So we need to add java options once restore of existing localconfig options done.

ZCS-11813 : Add Java options in zmsetup.pl for upgrade

---

instructions/bundling-scripts/zimbra-core.sh

**Problem Statement**
Create CLI utility to provide CLI interface for S3ConfigBucket Soap requests
**Solution**
Created new class and file named "VolumeS3ConfigCLI" which is CLI interface for s3BucketConfig requests

ZCS-11437 Add new CLI to manage global S3 buckets

---

instructions/bundling-scripts/zimbra-store.sh
rpmconf/Install/zmsetup.pl

related PR: https://github.com/Zimbra/zm-network-build/pull/21

ZCS-11847 : remove old com_zimbra_smime zimlet

---

instructions/bundling-scripts/zimbra-core.sh

ZCS-11694 : Add file shared with me system folder

ZCS-11694 : Add file shared with me system folder

---

instructions/bundling-scripts/zimbra-core.sh
instructions/bundling-scripts/zimbra-store.sh
rpmconf/Upgrade/zmupgrade.pm

Feature :- Added files for perl script that sends mail to configured admin

ZCS-11602 : Adding perl script in build for sending email

---

instructions/bundling-scripts/zimbra-store.sh

Removed zmmdmnotificationmail which is not used anymore

ZCS-12009 : removed zmmdmnotification from script

---

rpmconf/Install/Util/utilfunc.sh

Create package repository for ZCS 10.0.0
```
deb [arch=amd64] https://repo.zimbra.com/apt/87 bionic zimbra 
deb [arch=amd64] https://repo.zimbra.com/apt/1000 bionic zimbra 
deb [arch=amd64] https://repo.zimbra.com/apt/1000-ne bionic zimbra
```

ZCS-12062 : add repository for ZCS 10.0.0

---

rpmconf/Install/Util/globals.sh
rpmconf/Install/Util/utilfunc.sh
rpmconf/Install/zmsetup.pl

ZCS-12081 remove zimlets as part of an upgrade to zimbra10
Remove the following zimlets:
1. zimbra-zimlet-briefcase-edit-lool
2. zimbra-zimlet-restore-contacts
3. zimbra-zimlet-duplicate-contacts

ZCS-12081 remove zimlets as part of upgrade to zimbra10

---

instructions/bundling-scripts/zimbra-ldap.sh
instructions/bundling-scripts/zimbra-proxy.sh
rpmconf/Env/sudoers.d/02_zimbra-ldap
rpmconf/Env/sudoers.d/02_zimbra-proxy
rpmconf/Spec/Scripts/zimbra-ldap.post
rpmconf/Spec/Scripts/zimbra-proxy.post

Related PR: https://github.com/Zimbra/zm-core-utils/pull/126 and https://github.com/Zimbra/zm-nginx-conf/pull/31

ZBUG-2867 Run nginx and ldap with lesser privileges
