Zimbra/zm-build

rpmconf/Install/Util/modules/packages.sh
fix yum package lookup  to use --show-duplicate and work around issue with cut command on RHEL 6 replaced by awk.
=> ZCS-1206: fix yum package lookup  to use --show-duplicate. 

rpmconf/Install/Util/modules/packages.sh
use  --showduplicates instead  --show-duplicate  which is not working on centOS 6
=> ZCS-1206: use  yum --showduplicates instead  --show-duplicate 

rpmconf/Install/Util/utilfunc.sh
removing chat/drive/zsp option when store is not installed
=> ZCS-1290: removing chat/drive/zsp option when store is not installed

instructions/FOSS_repo_list.pl
`zmlocalconfig` has changed in **zm-core-utils** on the feature/imap
branch.
=> ZCS-1373:need zm-core-utils for zmlocalconfig

instructions/bundling-scripts/zimbra-store.sh
ZCS-1350: Add ZCO and Migration binaries in builds
- Included ZCO and Migration binaries in the build
- Tested /opt/zimbra/jetty-distribution-9.3.5.v20151012/webapps/zimbra/downloads contents
- Tested all the links of https://<server>/downloads/index.html
- Tested all the links of https://<server>:7071/zimbraAdmin/ -> Tools & Migration -> Download links.
=> ZCS-1350: Add ZCO and Migration binaries in builds

rpmconf/Install/zmsetup.pl
Change to default behavior of the `IMAPD Configuration` config
section to *not* enable the `Add to upstream IMAP Servers?` by default.
NOTE: For proper operation after installation to occur, this PR assumes that the work for ZCS-1494 has been merged.
=> ZCS-1480 Change default imapd config option

rpmconf/Upgrade/zmupgrade.pm
I don't think these fallbacks are ever used.  That's probably why nobody
noticed that one of tham can't work at all.
This code needs some cleanup but I don't want to touch that hornet's nest.
=> Fix fallbacks for zimbra_tmp_directory in zmupgrade

rpmconf/Upgrade/zmupgrade.pm
-removed the dependency to edit zmupgrade.pm file if any extra upgrade steps are not needed for that particular release.
-In case of extra upgrade steps for any release we need to add upgrade function and update the respective hash table with release name and update function name.
-created a different hash table for mysql update.
-deleted upgrade function which did not perform any upgarde.
=> ZCS-1456: Need to automate the manual effort needed to add upgrade reference in zmupgrade.pm

instructions/FOSS_staging_list.pl
Some of the build changes made on develop broke the zimbra-imapd build.
Had to update FOSS_staging_list so that the store-conf directory
gets properly staged.
=> ZCS-1443 Fix zimbra-imapd build

rpmconf/Install/zmsetup.pl
New attribute for zimbraNetworkMobileNGEnabled , this attribute will be TRUE on fresh install and FALSE on upgrade from version below 8.8.0.
=> ZCS-1709: Add attribute zimbraNetworkMobileNGEnabled  for zextras mobile components

rpmconf/Install/zmsetup.pl
Disabled attribute "zimbraNetworkMobileNGEnabled" when "zimbra-network-modules-ng" is not installed.
=> ZCS-1902: Disable attribute "zimbraNetworkMobileNGEnabled" when "zimbra-network-modules-ng" is not installed.

instructions/FOSS_staging_list.pl
FOSS_staging_list.pl
- add publish-local target for zm-timezones
- move it up in the order to make sure it is compiled first before zm-web-client and zm-admin-console
=> ZCS-1661 Move zm-timezone compilation step ahead of zm-web-client and zm-admin-console

instructions/FOSS_repo_list.pl
ZCS-1790 involved a change to the zm-ssdb-ephemeral-store repo, so we have to re-introduce a feature/imap branch again.
=> ZCS-1790: Build zm-ssdb-ephemeral-store from feature/imap

instructions/FOSS_repo_list.pl, instructions/FOSS_staging_list.pl
ZCS-1955: Update build scripts to use zm-admin-ajax instead of zm-ajax for admin console.
Changeset:
* FOSS_repo_list.pl: Adding entry for zm-admin-ajax repository.
* FOSS_staging_list.pl: Adding entry for zm-admin-ajax repository with ant targets to be called for getting the artifacts required by zm-admin-console.
=> ZCS-1955: Update build scripts to use zm-admin-ajax instead of zm-ajax for admin console.

rpmconf/Upgrade/zmupgrade.pm
Changed made: mysql_upgrade  will execute after each upgrade.
This will execute only if their is a database upgrade. 
In case the database is already upgarded, it exits within few seconds giving below message:
"This installation of MySQL is already upgraded to 10.1.25-MariaDB, use --force if you still need to run mysql_upgrade"
=> ZCS-2276: Bug 107976: Missing/failing mysql_upgrade step when upgrading to 8.7.x

rpmconf/Install/Util/utilfunc.sh, rpmconf/Install/zmsetup.pl
Upgraded from 8.7.6_GA_1776 - first selecting to install zimbra-imapd
then selecting not to install it.
In the first case, zimbra-imapd runs but doesn't do anything, imapd.log contains the line:
imap - ImapDaemon: This server not member of pool. Check zimbraReverseProxyUpstreamImapServers.
`zmcontrol status` reports the daemon  as Running.
Confirmed using openssl that connected to the embedded IMAP server and select a folder.  With IMAP tracing enabled, confirmed that the local variant was in use.
With the 2nd installation, confirmed that the imap daemon is not referenced in `zmcontrol status`
and no imapd.log file is created.  Again, confirmed that openssl connects to the embedded local IMAP server and can select a folder.
The above is the desired behavior as I understand it.
=> ZCS-2839 and ZCS-2885 zimbra-imapd installation

rpmconf/Install/Util/utilfunc.sh
This should be the default already, the installer requires port 11371 though because the keyserver was specified explicitly.
=> Bug 107192: Switch to port 80 to retrieve package signing key from keyserver

rpmconf/Install/zmsetup.pl
Enabled below modules on fresh install when "zimbra-network-modules-ng" is installed.
zimbraNetworkMobileNGEnabled, 
zimbraNetworkBackupNGEnabled, 
zimbraNetworkHSMNGEnabled
=> ZCS-3077: Updated install and upgrade script to use new NGModule attributes

rpmconf/Install/zmsetup.pl
* If zimbra-network-modules-ng not installed zimbraNetwork(Modules/Mobile/Admin)NGEnabled is false.
* Fresh install with zimbra-network-modules-ng zimbraNetwork(Modules/Mobile/Admin)NGEnabled is true.
* Upgrade with zimbra-network-modules-ng zimbraNetworkModulesNGEnabled is true where as mobile and admin false.
=> ZCS-3226: Updated NG parameter in fresh install as per new changes.

rpmconf/Install/Util/utilfunc.sh, rpmconf/Upgrade/zmupgrade.pm
On upgrade, see this in the logs and the right value is set afterwards:
zmsetup.log:Thu Oct 26 14:30:25 2017 *** Running as zimbra user: /opt/zimbra/bin/zmprov -r -m -l mcf  zimbraImapLoadBalancingAlgorithm 'AccountIdHash'
=> ZCS-3269 zimbraImapLoadBalancingAlgorithm corrected in config

README.md
Added package ant-junit for CentOS 7 to the system setup instructions on line 49. Not having ant-junit will fail the build process with a class not found error.
=> Added ant-junit CentOS 7 package to setup instructions

rpmconf/Install/zmsetup.pl
Update to zmsetup.pl to fetch the global value of `zimbraEphemeralBackendURL` from LDAP if it is set during the installation of nodes which connect to LDAP to pre-populate installer settings.
This ensures that the menu option shows that it will be using an external ephemeral backend and also displays the current setting for the option.
Note: I decided I didn't want to distinguish between a user setting the value and the installer populating the existing value into the options.  If this is desired it can be accomplished with some additional changes.
=> ZCS-2189 retrieve ephemeral settings from ldap

instructions/bundling-scripts/zimbra-core.sh
This library is not actually used and its presence is
creating a conflict with the ZooKeeper library we are using.
=> ZCS-4346, ZCS-4315 Remove zkclient from zimbra-core

instructions/bundling-scripts/zimbra-store.sh
Per @Prashantsurana have removed the permissions updates for the templates. NETWORK build completes with no errors.
I am going to do a quick test install first to make sure the affected directories have the correct permissions so I don't want to merge this yet.  Just wanted to publish it now for comment, and to make sure I am on the right track.
These are the type of build issues that @rupalid had reported (prior to this update).  The following is just a snippet:
error: File not found: /home/build/stash/.staging/RHEL6_64-TURING-888-20180316074126-NETWORK-1989/zm-build/storebuild/opt/zimbra/conf/templates/templates
error: File not found: /home/build/stash/.staging/RHEL6_64-TURING-888-20180316074126-NETWORK-1989/zm-build/storebuild/opt/zimbra/conf/templates/templates/abook
error: File not …
=> PREVIEW: Remove the templates updates from RHEL packaging

rpmconf/Upgrade/zmupgrade.pm
This was causing the schema updates for zextras to not be installed and thus breaking upgrade.
=> Updated expected schema version to 109.

rpmconf/Install/Util/utilfunc.sh
This change was suggested by Prashant as a temporary method to get around the fact that we are including the same files in multiple RPMs which RPM correctly identifies as a conflict.
Since they are exactly the same file it was decided that it doesn't matter which package ultimately places the file on disk since each file that has a conflict is exactly the same in both packages.
Note: This appears to have ramifications to the upgrade process from 8.8.7 at this time.  This is unfortunate since this is the case it was intended to resolve.  This is being opened to get additional eyes on this.
=> use rpm instead of yum for install

rpmconf/Install/zmsetup.pl, rpmconf/Upgrade/zmupgrade.pm
LDAP was not runnable with previous change in some upgrade scenarios
when was setting `zimbraLDAPSchemaVersion`
=> ZCS-4592:configLDAPSchemaVersion from zmupgrade

rpmconf/Upgrade/zmupgrade.pm
Not yet tested!
Philosophy is that anything that would have successfully managed to set
global config before must have LDAP in an OK state, so if we add a call
to `configLDAPSchemaVersion` from there, LDAP should be able to
do the trick.
For this to work, need to set the tracker variable in
`configLDAPSchemaVersion` at the start of it otherwise would loop.
=> ZCS-4592:zimbraLDAPSchemaVersion 3rd attempt

rpmconf/Patch/conf/zmpatch.xml
* Changed code under zm-mailbox/soap so need zimbrasoap.jar
* Previously had duplicate references to ZCS-4859, so re-used one of
those.
=> ZCS-4848:backPort 3055 toi 8.7.11.p3

rpmconf/Install/zmsetup.pl
… multiple value field in zmsetup.pl
One of the commits where this problem was introduced was: 3e59e1604f6fb042cb1a88f32259479b7c383d6f
( ZCS-3192 add strict server name enforcement to installer  )
=> zimbraReverseProxyStrictServerNameEnabled is not a multivalued attribute

instructions/FOSS_repo_list.pl, instructions/FOSS_staging_list.pl
Upgrading OWASP library to latest version, which resolves ZBUG-1148
Added fix for ZCS-7497 in new owasp library
Ref PRs:
https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/1
https://github.com/Zimbra/zm-zcs-lib/pull/54
https://github.com/Zimbra/zm-mailbox/pull/963
=> ZBUG-1148:Loosing table format with owasp sanitizer

instructions/bundling-scripts/zimbra-core.sh
Replacing migration script name change for ZCS-8670 with ZCS-8730.
Testing to be done by QA:
test migration script
Ref PR:
https://github.com/Zimbra/zm-mailbox/pull/1026
https://github.com/Zimbra/zm-db-conf/pull/10
=> ZCS-8730:database changes to support ABQ

instructions/bundling-scripts/zimbra-store.sh
Added `custom-mimetypes.xml` in `store-conf` which will be copied over to the `/opt/zimbra/conf` directory where we can be able override the existing mimetypes and can be able to map the content-type to any of the extensions with a higher magic priority.
**Related PR:**
[zm-zcs-lib](https://github.com/Zimbra/zm-zcs-lib/pull/72)
[zm-mailbox](https://github.com/Zimbra/zm-mailbox/pull/1132)
=> ZCS-10322: Added custom-mimetypes.xml

instructions/bundling-scripts/zimbra-core.sh, rpmconf/Upgrade/zmupgrade.pm
bringing eas and abq from zx to z9
branch `eas_zx` is used for below repositories
1. zm-mailbox
2. zm-sync-common
3. zm-sync-store
4. zm-sync-client
5. zm-sync-tools
6. zm-db-conf
7. zm-build
=> EAS - Bring 16.0/16.1 support to z9

rpmconf/Install/Util/utilfunc.sh
Problem:
While upgrading rabbitmq is removed first, but not picked again for installation.
FIX :
Check if onlyoffice is being upgraded. If it is being upgraded, install rabbit-mq
=> bugfix/ZCS-10808 : Install rabbit-mq while upgrading

rpmconf/Install/Util/utilfunc.sh, rpmconf/Install/zmsetup.pl
**Problem:**
Getting below one in setup log
Checking if the NG started running...done.
**Fix:**
zxsuiteIsAvailable() calling to check ng-backup enabled or not. As we are disabling ng-modules this(zxsuiteIsAvailable()) call is not required.
=> changes for 9.1.0

rpmconf/Install/Util/utilfunc.sh
There is an extra `fi` which is causing the installation to fail.
=> ZCS-10808-1 :Install rabbit-mq while upgrading

instructions/bundling-scripts/zimbra-core.sh, instructions/bundling-scripts/zimbra-store.sh, rpmconf/Install/zmsetup.pl
**Problem:**
A log about an error on jetty is not written in zmmailboxd.out on ZCS 9.0.0 Patch 13 and later.
**Root cause:**
`/opt/zimbra/jetty_base/common/lib/slf4j-api-1.7.30.jar` has been added since Patch 13.
On Patch12 or prior, org.eclipse.jetty.util.log.class is not defined, org.slf4j.Logger does not exist in classpath, and then org.eclipse.jetty.util.log.StdErrLog is used.
(zmmailboxd.out)
```
2021-12-06 20:24:53.097:INFO::main: Logging initialized @1342ms to org.eclipse.jetty.util.log.StdErrLog
```
After Patch 13, org.eclipse.jetty.util.log.class is not defined, org.slf4j.Logger exists in classpath, and then org.eclipse.jetty.util.log.Slf4jLog is used. However, no SFL4J binding is defined. Then it falls back to NOP or /dev/null.
(zmmailboxd.out)
```
SLF4J: Failed to load class …
```
=> Fix for ZCS-11090

rpmconf/Build/get_plat_tag.sh
CentOS Linux 8 reaches EOL on 2021-12-31 and is superseeded by Rocky Linux 8 as alternative bug-for-bug compatible RHEL 8 rebuild.
=> Add Rocky Linux 8

rpmconf/Install/zmsetup.pl
Problem: It would not allow different server name to be added in case of onlyoffice being installed with mailbox
Test: 
Changed zmsetup.pl : `createOnlyofficeMenu` to allow overwrite
=> ZCS-10890 : Allow onlyoffice server name change

rpmconf/Install/Util/globals.sh, rpmconf/Install/Util/utilfunc.sh
As a developer I want a system where we can create custom build from jenkins including custom changes, which can be installed in lab machine for testing and development process.
Currently when we create custom build it has all changes in the package but at installation time zimbra-patch, zimbra-mta-patch, zimbra-proxy-patch packages overwrites those changes with older files, so we may introduce an extra option in installation time to install zimbra-patch, zimbra-mta-patch, zimbra-proxy-patch packages or not, this option should be visible only when installing this build in lab machines, this option should not be present for customers.
=> ZCS-11305: option to choose installation of patch packages when installing custom build in lab machines

rpmconf/Spec/zimbra-store.deb, rpmconf/Spec/zimbra-store.spec
Upgrade jetty to 9.4.46.v20220331
Related PR's:
https://github.com/Zimbra/zm-zcs-lib/pull/92
https://github.com/Zimbra/zm-jetty-conf/pull/18
https://github.com/Zimbra/zm-mailbox/pull/1267
=> ZBUG-2633:Upgraded jetty to 9.4.46.v20220331

rpmconf/Install/Util/globals.sh
9.0.0 FOSS Build Installer shouldn't install zimbra-patch, zimbra-mta-patch, zimbra-proxy-patch packages
=> ZCS-11304 : Changes for 9.0.0 FOSS Build

instructions/bundling-scripts/zimbra-core.sh
**zm-build changes**
Problem Statement
Need new column in zimbra.volume table
Solution
Added new migration file which shall allow us to create a new column in zimbra.volume table
=> ZCS-11426 Need new column in zimbra.volume table

rpmconf/Upgrade/zmupgrade.pm
Problem Statement:
Store Type column should get creating while installing fresh ZIMBRA build (not upgrading)
Solution:
Added store_type column entry in volume table for database
Please review this along with https://github.com/Zimbra/zm-db-conf/pull/26
=> ZCS-11697 StoreType colume should get created while installing fresh build

instructions/bundling-scripts/zimbra-store.sh
zm-store-manager jar created with the latest integration id, so this should be handled with regex.
=> ZCS-11775: zm-store-manager jar created with the latest integration id, so this should be handled with regex.

rpmconf/Upgrade/zmupgrade.pm
Upgrade from 10.0.0 BETA to latest BETA not allowed. User should be able to upgrade 10.0 from old version to latest BETA version.
Restoring existing configuration file from /opt/zimbra/.saveconfig/localconfig.xml...done
Installing /opt/zimbra/conf/ZCSLicense.xml
Operations logged to /tmp/zmsetup.20220817-121323.log
Adding /opt/zimbra/conf/ca/ca.pem to cacerts
Upgrading from 10.0.0_BETA_4401 to 10.0.0_BETA_4404
ERROR: Upgrading from a ZCS version less than 7.0.0_GA is not supported
UPGRADE FAILED - exiting.
=> ZCS-11980 : Fix regexp to get correct build versions

rpmconf/Install/Util/utilfunc.sh
Default option for hosted immail chat/video package installation should be No.
Install chat and video features - Set default as N instead of Y
=> ZCS-12028 : Default option for Install chat and video features is No

rpmconf/Install/Util/utilfunc.sh, rpmconf/Install/install.sh
- As an admin, when upgrading NG server to Z-10, I should get a warning about presence of NG modules and the upgrade should be aborted. I should be able to use --skip-ng-check option and continue the upgrade.
- Installer should detect if NG is installed or not. If its not installed then the upgrade should continue.
- If NG is installed Abort the upgrade.
- Display this error on screen in RED color.
`NG Modules detected on your system. If you continue with this upgrade, NG module packages and the data will be deleted.
If you want to preserve NG data, consider using migration or rolling upgrade strategy for upgrading your system. For more information, please contact Zimbra Support.
If you still want to continue, start installation using --skip-ng-check.`
- If admin provides …
=> ZCS-12128 : Add a pre-upgrade check to detect NG modules installation

rpmconf/Spec/Scripts/zimbra-ldap.post, rpmconf/Spec/Scripts/zimbra-proxy.post
- After upgrade proxy is not starting as log files are created with root permission
- issue is only happening in server where log rotation has not run once, as log rotation updates file permissions with zimbra user
Related PR https://github.com/Zimbra/zm-core-utils/pull/127
=> ZCS-12164 Change permission of nginx log files

rpmconf/Install/Util/globals.sh, rpmconf/Install/Util/utilfunc.sh
**Issue 1:**
Skip NGModules check for uninstall Zimbra
**Issue 2:**
FOSS Build should not ask to install immail
**Issue 3:**
Change in order of ze-extras packages remove.
zimbra-zimlet-briefcase-edit-lool package should be remove after zimbra-drive-modern, zimbra-docs-modern packages remove. Because zimbra-drive-modern, zimbra-docs-modern are depends on zimbra-zimlet-briefcase-edit-lool.
=> ZCS-12219 : Skip NGModules check for uninstall Zimbra

instructions/FOSS_staging_list.pl
- zm-help and zm-downloads repos doesn't have any ant target for creating artifacts
- and zm-build repo just copies all files from above repos to include it as part of final build
- but in this inclusion zm-build is using cp command which copies .git directories as well
- so we are excluding .git directories when copying data and creating build
=> ZBUG-2974 Exclude .git directories from build
